import hoodieUrl from "../img/work/hoodie.png";
import trikoUrl from "../img/work/longTriko.png";
import shortTriko from "../img/work/shortTriko.png";
import helmetUrl from "../img/safety/helmet.png";
import yellow from "../img/safety/yellowVest.png";
import orange from "../img/safety/orangeVest.png";
import manager from "../img/safety/manager.png";
import cargo from "../img/work/cargoPants.png";
import cargoBack from "../img/work/cargoPantsBack.png";
import kenguru from "../img/work/kenguru.png";
import yellowBack from "../img/safety/yellowVestBack.png";
import orangeBack from "../img/safety/orangeVestBack.png";
import managerBack from "../img/safety/managerBack.png";
import softShellCoat from "../img/work/coat1.png";
import softShellCoatBack from "../img/work/coat1Back.png";
import kenguruBack from "../img/work/kenguruBack.png";
import zipper from "../img/work/zipperHoodie.png";
import drifitShort from "../img/work/drifitShort.png";
import drifitShortBack from "../img/work/drifitShortBack.png";
import drifitLong from "../img/work/drifitLong.png";
import drifitLongBack from "../img/work/drifitLongBack.png";
import hermonit from "../img/work/hermonit.png";
import fleese from "../img/work/plizOneSide.png";
import fleeseDouble from "../img/work/plizDoubleSide.png";
import labCoat from "../img/work/mictaron.png";
import halfApron from "../img/work/halfSinar.png";
import fullApron from "../img/work/fullSicar.png";
import chef from "../img/work/chef.png";
import drifitStripes from "../img/safety/drifitStripes.png";
import bottle from "../img/work/bottle.png";
import managerYellow from "../img/safety/managerYellow.png";
import managerYellowBack from "../img/safety/managerYellowBack.png";

export const PRODUCTS = [
  {
    slug: "hoodie-zipper",
    name: "קפוצ׳ון רוכסן",
    price: 85,
    img: zipper,
    colors: ["לבן", "נייבי", "אפור", "שחור"],
    sizes: ["S", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    category: "workwear",
    season: "חורף",
    type: "hoodie",
    logoAllowed: true,
    isBlocked: false,
  },
  {
    slug: "long-triko",
    name: "טריקו ארוך",
    price: 60,
    img: trikoUrl,
    colors: ["לבן", "נייבי", "אפור", "שחור"],
    sizes: ["S", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    category: "workwear",
    season: "קיץ, חורף",
    type: "shirt",
    logoAllowed: true,
    isBlocked: false,
  },
  {
    slug: "short-triko",
    name: "טריקו קצר",
    price: 55,
    img: shortTriko,
    colors: ["לבן", "נייבי", "אפור", "שחור"],
    sizes: ["S", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    category: "workwear",
    season: "קיץ, חורף",
    type: "shirt",
    logoAllowed: true,
    isBlocked: false,
  },
  {
    slug: "safety-helmet",
    name: "קסדת בטיחות",
    price: 80,
    img: helmetUrl,
    colors: ["אפור"],
    sizes: ["ONE SIZE"],
    category: "safety",
    season: "אין",
    type: "helmet",
    logoAllowed: false,
    isBlocked: false,
  },
  {
    slug: "vest-yellow",
    name: "אפוד זוהר צהוב",
    price: 45,
    img: yellow,
    backImg: yellowBack,
    colors: ["צהוב"],
    sizes: ["ONE SIZE"],
    category: "safety",
    season: "אין",
    type: "vest",
    logoAllowed: true,
    isBlocked: false,
  },
  {
    slug: "vest-orange",
    name: "אפוד זוהר כתום",
    price: 45,
    img: orange,
    backImg: orangeBack,
    colors: ["כתום"],
    sizes: ["ONE SIZE"],
    category: "safety",
    season: "אין",
    type: "vest",
    logoAllowed: true,
    isBlocked: false,
  },
  {
    slug: "manager-vest",
    name: "אפוד מנהלים כתום",
    price: 100,
    img: manager,
    backImg: managerBack,
    colors: ["כתום"],
    sizes: ["ONE SIZE"],
    category: "safety",
    season: "אין",
    type: "vest",
    logoAllowed: true,
    isBlocked: false,
  },
  {
    slug: "manager-vest-orange",
    name: "אפוד מנהלים כתום",
    price: 100,
    img: manager,
    backImg: managerBack,
    colors: ["כתום"],
    sizes: ["ONE SIZE"],
    category: "safety",
    season: "אין",
    type: "vest",
    logoAllowed: true,
    isBlocked: false,
  },{
    slug: "manager-vest-yellow",
    name: "אפוד מנהלים כתום",
    price: 100,
    img: managerYellow,
    backImg: managerYellowBack,
    colors: ["צהוב"],
    sizes: ["ONE SIZE"],
    category: "safety",
    season: "אין",
    type: "vest",
    logoAllowed: true,
    isBlocked: false,
  },
  {
    slug: "cargo-pants",
    name: "מכנסי דגמ\"ח לעבודה",
    price: 60,
    img: cargo,
    backImg: cargoBack,
    colors: ["שחור", "נייבי"],
    sizes: ["S", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    category: "workwear",
    season: "קיץ, חורף",
    type: "pants",
    logoAllowed: false,
    isBlocked: false,
  },
  {
    slug: "hoodie-kenguru",
    name: "קפוצ'ון קנגורו",
    price: 85,
    img: kenguru,
    backImg: kenguruBack,
    colors: ["לבן", "נייבי", "אפור", "שחור"],
    sizes: ["S", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    category: "workwear",
    season: "חורף",
    type: "hoodie",
    logoAllowed: true,
    isBlocked: false,
  },
  {
    slug: "softshell-coat",
    name: "מעיל סופטשל לעבודה",
    price: 180,
    img: softShellCoat,
    backImg: softShellCoatBack,
    colors: ["שחור", "נייבי"],
    sizes: ["S", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    category: "workwear",
    season: "חורף",
    type: "jacket",
    logoAllowed: true,
    isBlocked: false,
  },
  {
    slug: "drifit-short",
    name: "חולצת דרייפיט קצרה",
    price: 50,
    img: drifitShort,
    backImg: drifitShortBack,
    colors: ["לבן", "נייבי", "אפור", "שחור"],
    sizes: ["S", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    category: "workwear",
    season: "קיץ, חורף",
    type: "shirt",
    logoAllowed: true,
    isBlocked: false,
  },
  {
    slug: "drifit-long",
    name: "חולצת דרייפיט ארוכה",
    price: 55,
    img: drifitLong,
    backImg: drifitLongBack,
    colors: ["לבן", "נייבי", "אפור", "שחור"],
    sizes: ["S", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    category: "workwear",
    season: "קיץ, חורף",
    type: "shirt",
    logoAllowed: true,
    isBlocked: false,
  },
    // === NEW from price sheet ===
  {
    slug: "storm-suit",
    name: "חרמונית",
    price: null,
    img: hermonit,
    colors: ["נייבי"],
    sizes: ["S", "L", "XL", "2XL", "3XL"],
    category: "workwear",
    season: "חורף",
    type: "overall",
    logoAllowed: true,
    isBlocked: true,
  },
  {
    slug: "fleece",
    name: "פליז",
    price: null,
    img: fleese,
    colors: ["שחור", "נייבי"],
    sizes: ["S", "L", "XL", "2XL", "3XL"],
    category: "workwear",
    season: "חורף",
    type: "fleece",
    logoAllowed: true,
    isBlocked: true,
  },
  {
    slug: "fleece-reversible",
    name: "פליז דו צדדי",
    price: null,
    img: fleeseDouble,
    colors: [
      "שחור/כחול",
      "שחור/כתום",
      "שחור/אדום",
      "שחור/רויאל",
      "שחור/בורדו",
      "שחור/ירוק"
    ],
    sizes: ["S", "L", "XL", "2XL", "3XL"],
    category: "workwear",
    season: "חורף",
    type: "fleece",
    logoAllowed: true,
    isBlocked: true,
  },
  {
    slug: "lab-coat",
    name: "מקטרונים",
    price: null,
    img: labCoat,
    colors: ["לבן"],
    sizes: ["S", "L", "XL", "2XL", "3XL"],
    category: "workwear",
    season: "קיץ",
    type: "coat",
    logoAllowed: true,
    isBlocked: true,
  },
  {
    slug: "half-apron",
    name: "סינר חצי",
    price: null,
    img: halfApron,
    colors: ["שחור", "אדום", "לבן"],
    sizes: ["ONE SIZE"],
    category: "workwear",
    season: "קיץ",
    type: "apron",
    logoAllowed: true,
    isBlocked: true,
  },
  {
    slug: "full-apron",
    name: "סינר שלם",
    price: null,
    img: fullApron,
    colors: ["שחור", "אדום", "לבן"],
    sizes: ["ONE SIZE"],
    category: "workwear",
    season: "קיץ",
    type: "apron",
    logoAllowed: true,
    isBlocked: true,
  },
  {
    slug: "chef-jacket",
    name: "ג'קט שף",
    price: null,
    img: chef,
    colors: ["שחור", "לבן"],
    sizes: ["ONE SIZE"],
    category: "workwear",
    season: "קיץ",
    type: "chef-jacket",
    logoAllowed: true,
    isBlocked: true,
  },
  {
    slug: "drifit-stripes",
    name: "דרייפיט פסים זוהרים",
    price: null,
    img: drifitStripes,
    colors: [
      "אדום",
      "אפור",
      "ירוק",
      "לבן",
      "כתום",
      "שחור",
      "כחול רויאל",
      "כחול כהה"
    ],
    sizes: ["S", "L", "XL", "2XL", "3XL"],
    category: "safety",
    season: "אין",
    type: "shirt",
    logoAllowed: true,
    isBlocked: true,
  },
  {
    slug: "thermal-bottle",
    name: "בקבוקים תרמיים",
    price: null,
    img: bottle,
    colors: ["לבן", "כסף", "שחור"],
    sizes: ["ONE SIZE"],
    category: "safety",
    season: "אין",
    type: "bottle",
    logoAllowed: true,
    isBlocked: true,
  },
];
